# Generated by Django 6.0.5 on 2026-06-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='position',
        ),
        migrations.RemoveField(
            model_name='student',
            name='salary',
        ),
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(default='Unknown', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
